import moment from 'moment';

const days = ['Today', 'Tomorrow', moment().add(2, 'days').format('ddd, MMM D')];
const times = ['9:00 AM', '11:10 AM', '12:00 PM', '1:50 PM', '4:30 PM', '6:00 PM', '7:10 PM', '9:45 PM'];

export const movies = [
    {
        title: 'Aquaman',
        poster: 'https://i.imgur.com/b1DNzTu.jpg',
        genre: 'Fantasy/Science Fiction',
        days,
        times,
    },
    {
        title: 'Spider-Man: Into the Spider-Verse',
        poster: 'https://i.imgur.com/a59k5U1.jpg',
        genre: 'Fantasy/Science Fiction',
        days,
        times,
    },
    {
        title: 'Creed II',
        poster: 'https://i.imgur.com/CzOQC9V.jpg',
        genre: 'Drama/Sport',
        days,
        times,
    },
    {
        title: 'Fantastic Beasts: The Crimes of Grindelwald',
        poster: 'https://i.imgur.com/A3BbAb4.jpg',
        genre: 'Drama/Fantasy',
        days,
        times,
    },
    {
        title: 'Bohemian Rhapsody',
        poster: 'https://i.imgur.com/hJYcDn8.jpg',
        genre: 'Drama/Biography',
        days,
        times,
    },
    {
        title: 'The Nun',
        poster: 'https://i.imgur.com/AtteNFU.jpg',
        genre: 'Mystery/Thriller',
        days,
        times,
    },
    {
        title: 'De Palma',
        poster: 'https://i.imgur.com/oOIa73M.jpg',
        genre: 'Documentary',
        days,
        times,
    },
    {
        title: 'Doctor Strange',
        poster: 'https://i.imgur.com/kyHDVOk.jpg',
        genre: 'Fantasy/Science Fiction',
        days,
        times,
    },
    {
        title: 'Eddie the Eagle',
        poster: 'https://i.imgur.com/GNrdAuF.jpg',
        genre: 'Drama/Sport',
        days,
        times,
    },
    {
        title: 'Pride and prejudice and zombies',
        poster: 'https://i.imgur.com/KhbG0Lw.jpg',
        genre: 'Thriller/Action',
        days,
        times,
    },
    {
        title: 'Finding Dory',
        poster: 'https://i.imgur.com/BTexHYJ.jpg',
        genre: 'Comedy/Adventure',
        days,
        times,
    },
    {
        title: 'Green Room',
        poster: 'https://i.imgur.com/Q0Ysh7L.jpg',
        genre: 'Crime/Thriller',
        days,
        times,
    },
    {
        title: 'Kubo and the Two Strings',
        poster: 'https://i.imgur.com/uTFCKZc.jpg',
        genre: 'Fantasy/Adventure',
        days,
        times,
    },
    {
        title: 'In a Valley of Violence',
        poster: 'https://i.imgur.com/DTtJ62G.jpg',
        genre: 'Drama/Western',
        days,
        times,
    },
    {
        title: 'O.J.: Made in America',
        poster: 'https://i.imgur.com/T8uc6x8.jpg',
        genre: 'Documentary',
        days,
        times,
    },
    {
        title: 'Rogue One: A Star Wars Story',
        poster: 'https://i.imgur.com/zOF2iYc.jpg',
        genre: 'Science Fiction/Action',
        days,
        times,
    },
    {
        title: 'Sing Street',
        poster: 'https://i.imgur.com/C3ExEb6.jpg',
        genre: 'Drama/Romance',
        days,
        times,
    },
    {
        title: 'Zoolander 2',
        poster: 'https://i.imgur.com/ejlIijD.jpg',
        genre: 'Comedy',
        days,
        times,
    },
];